---
title: "linear_models"
author: "yh3429"
date: "2022-11-10"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```
## Model fitting

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```


```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

## Tidying output

```{r , message=FALSE, results='hide'}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

### To get nicely format

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  knitr::kable(digits = 3)
```

#### Let's chage reference category.

```{r}
fit = 
  nyc_airbnb %>% 
  mutate (
    borough = fct_infreq(borough)      
  ) %>% 
  lm(price ~ stars + borough, data = .)

# the above steps want to change reference category #
# the reference group is the most common group #

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  knitr::kable(digits = 2)

fit %>% 
  broom::glance() %>% 
  select(AIC)

```

## Diagnostics

```{r}

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) + geom_violin()+ylim(-250, 250)

```


## Hypothesis testing

#### one coefficient (let's say one variable "stars")

```{r}
fit %>% 
  broom::tidy()

```

### more coefficients

```{r}
fit_null = lm (price ~ stars, data = nyc_airbnb)
fit_alt = lm (price ~ stars+borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## Room type by borough

#### Interaction...?

```{r}
fit =
  nyc_airbnb %>% 
  lm (price ~ stars+borough * room_type, data = .) 

fit%>% broom::tidy()
```


#### so...can we fit models by borough...? (Here, for example, to have four different linear models by different four boroughs) 

```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(data = -borough) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results)

nest_lm_res
```

#### Quick double check

```{r}
nyc_airbnb %>% 
  filter (borough == "Bronx") %>% 
  lm (price ~stars + room_type, data = .) %>% 
  broom::tidy()

nyc_airbnb %>% 
  filter (borough == "Queens") %>% 
  lm (price ~stars + room_type, data = .) %>% 
  broom::tidy()
```

